### ISSUE TITLE
Invalid MIC on Relay Feature

### ISSUE THREAD

**Issue by EduardoPfeifer** [Lora-net/SWL2001#11]
Hey!
I am testing the new branch (feature/relay) with the ChirpStack network server and I am getting some issues after the device is successfully connected to the NS through the Relay RX device.

After a `TX DONE on RXR` (Join Accept sent to the device), the Relay RX starts a CAD 1s.

The device, after a Join accept, starts an Alarm to send uplink in 60 s. When the device sends the WOR, the Relay tells me a
`Invalid MIC` and `Unknown ED (0x017501A3)`.

What am I doing wrong? Is this behavior expected or could it be a possible bug?

Thanks!

**Comment by EduardoPfeifer** [comment]
Hi!

I found the problem, it was my setting on Chirpstack about `ForwardListReq`.

**Comment by Mathannbala** [comment]
Hi @EduardoPfeifer, could you be kind enough to clarify more on the settings of Chirpstack with regards to the ForwardListReq? Im encountering the same issue of Invalid MIC and Unknown ED. As i do not own the Chirpstack server, i would need to raise it to the owners for the appropriate changes. Hope you can assist me on this. Thanks
![image](https://github.com/Lora-net/SWL2001/assets/97488545/4c8e7a50-1f08-4a7f-b785-d9e079be8023)
![invalid MIC-Unknown ED](https://github.com/Lora-net/SWL2001/assets/97488545/4ecf686a-5305-4f04-98ab-cd43466defee)

**Comment by lbm-team** [comment]
Hi @Mathannbala , 

In Chirpstack, you need to link your end-device and your relay together

To do that,select you ED  in your application , click on "selected device" then "Add to relay"
![image](https://github.com/Lora-net/SWL2001/assets/127109064/8b06c96a-7060-4aee-99dc-1ec071423a2b)

I hope it help

**Comment by Mathannbala** [comment]
@lbm-team Thank you so much for the prompt response, I've done so and my end device is able to connect via the relay. However, I noticed that after a certain amount of transmissions, I'm seeing " missed data" on the relay, not sure if this is expected behaviour
