### ISSUE TITLE
The stack hangs when an undefined command is received.

### ISSUE THREAD

**Issue by Ramin-Mardani** [Lora-net/SWL2001#14]
https://github.com/Lora-net/SWL2001/blob/45e19e5bf783bf874b8c9825b76c4c5befa8bcba/smtc_modem_core/lorawan_packages/fuota_packages/lorawan_remote_multicast_setup_package.c#L685

The stack hangs inside the function above when I send a command that is not defined by the LoRaWAN specification on Port 200. For example, command 0x06 without any payload. Please refer to "**LoRaWAN® Remote Multicast Setup
Specification TS005**"

I guess it is because of the missing default in the function mentioned above.

**Comment by MpmTwtg** [comment]
This also happens in:

https://github.com/Lora-net/SWL2001/blob/45e19e5bf783bf874b8c9825b76c4c5befa8bcba/smtc_modem_core/lorawan_packages/fuota_packages/lorawan_fmp_package.c#L479

https://github.com/Lora-net/SWL2001/blob/45e19e5bf783bf874b8c9825b76c4c5befa8bcba/smtc_modem_core/lorawan_packages/fuota_packages/lorawan_fragmentation_package.c#L397

And the same for the `fuota_packages_v2 package`

**Comment by lbm-team** [comment]
Thank you for your feedback, this issue will be fixed in the next release

**Comment by lbm-team** [comment]
Hi @Ramin-Mardani, @MpmTwtg

This issue is now fixed in new v4.3.0 release and mentioned in [CHANGELOG](https://github.com/Lora-net/SWL2001/blob/v4.3.0/CHANGELOG.md).

Once more thanks for your report
