### ISSUE TITLE
NotifyNewEndDeviceReq does not contain the MAC command ID

### ISSUE THREAD

**Issue by adriansmares** [Lora-net/SWL2001#17]
When LBM is compiled with relay RX support, the relay can choose to notify the Network Server that an unknown end device has sent a wake-on-radio frame. The current LBM implementation achieves this by sending an uplink on FPort=0, which is fine, but the payload is not prepended by the MAC command ID, which makes parsing on the Network Server not possible.

https://github.com/Lora-net/SWL2001/blob/c4f386ac54b3e35f45b8ba7502207faa6f634921/smtc_modem_core/lr1mac/src/relay/relay_rx/relay_rx.c#L1304-L1332

Notice that the first element in the buffer is related to the device address of the unknown device, not the MAC command ID (which is decimal 70).

<img width="669" alt="image" src="https://github.com/Lora-net/SWL2001/assets/36161392/9fa66b2c-2adf-4c4a-987e-867794141a75">

It is also the case that this implementation cannot piggy-back an existing uplink (via `FOpts`), but that's another problem.

**Comment by lbm-team** [comment]
Hello,

This issue was solved in the release v4.4.0-feature-relay.
