### ISSUE TITLE
Remote Multicast Package - Incorrect answer when multiple commands including McGroupStatusReq

### ISSUE THREAD

**Issue by HernandoSergio** [Lora-net/SWL2001#20]
The position for the multicast group data in the MxGroupStatusReq is fixed:

https://github.com/Lora-net/SWL2001/blob/45e19e5bf783bf874b8c9825b76c4c5befa8bcba/smtc_modem_core/lorawan_packages/fuota_packages/lorawan_remote_multicast_setup_package.c#L714

That line should be:
`uint8_t index_tmp = ans_index+1;`

**Comment by lbm-team** [comment]
Good catch, this issue will be fixed in the next release

**Comment by lbm-team** [comment]
Hi @HernandoSergio 

This issue is now fixed in new v4.3.0 release and mentioned in [CHANGELOG](https://github.com/Lora-net/SWL2001/blob/v4.3.0/CHANGELOG.md).

Once more thanks for your report
