### ISSUE TITLE
Multicast Class B Session request command fails

### ISSUE THREAD

**Issue by HernandoSergio** [Lora-net/SWL2001#22]
The Multicast Class B session request command fails.

https://github.com/Lora-net/SWL2001/blob/45e19e5bf783bf874b8c9825b76c4c5befa8bcba/smtc_modem_core/lorawan_packages/fuota_packages/lorawan_remote_multicast_setup_package.c#L890C1-L897C25

The validation of the frequency and the DR is done wrong, it shoul be checked with "ERRORLORAWAN" as the api validation functions return "OKLORAWAN" (0) or  "ERRORLORAWAN" (-1) instead of true or false.

**Comment by lbm-team** [comment]
Hi @HernandoSergio 
Thanks for your message.
Good catch!
This issue will be solved in next LBM release.

**Comment by lbm-team** [comment]
Hi @HernandoSergio

This issue is now fixed in new v4.3.0 release and mentioned in [CHANGELOG](https://github.com/Lora-net/SWL2001/blob/v4.3.0/CHANGELOG.md).

Once more thanks for your report
