### ISSUE TITLE
The stack doesn't complete a FUOTA process

### ISSUE THREAD

**Issue by Ramin-Mardani** [Lora-net/SWL2001#23]
Hello,

regarding FUOTA I realized that the stack is not able to reconstruct the update packets once at least one packet is lost.
I am using the LBM stack with commit id 45e19e5bf783bf874b8c9825b76c4c5befa8bcba
My end device is located next to the gateway that is connected to our application server (ChirpStack). 

I have following settings in our project:
  - SX126X
REGION_EU_868
RP2_101
SMTC_D2D
ADD_D2D
NUMBER_OF_STACKS=1
ADD_FUOTA
ALLOW_FUOTA
ADD_CLASS_B
ADD_CLASS_C
ADD_SMTC_ALC_SYNC
SMTC_MULTICAST
FRAG_MAX_NB=850
ENABLE_FUOTA_MPA
ENABLE_FUOTA_FMP

Following is my process:

- I turn on my end device. This connects to the application server .
- I start a FUOTA deployment with the following parameters:
```
    payload = File.ReadAllBytes( "my_new_firmware.bin" );
    fragmentSize = 232u;
    fragmentationRedundancy = 2;
    delayPerFragment = TimeSpan.FromSeconds(5);
    unicastAttemptCount = 2;
    unicastTimeout = TimeSpan.FromMinutes(11);
    MulticastGroupType = MulticastGroupType.ClassC,
    MulticastDr = 5,
    MulticastFrequency = 868100000,
    MulticastGroupId = 0,
    MulticastTimeout = multicastTimeout,
    MulticastRegion = Region.Eu868,
```

- As soon as the next uplink comes from the end device, fuota-related messages are exchanged between the end device and the server on ports 200 and 201. 
- After some minutes the FUOTA process is started
- The stack changes into class C and it receives fragments
- (In most cases) at the beginning of the process 1 or 2 packets are lost (Number of missed packets = 1)
- The stack continues and receives all fragments (in my case 783 + 2 additional fragments)
- The stack doesn't generate `SMTC_MODEM_EVENT_LORAWAN_FUOTA_DONE ` event
- After some minutes later the class c timeout is reached and the stack generate `SMTC_MODEM_EVENT_NO_MORE_MULTICAST_SESSION_CLASS_C ` event

In this case, the stack does nothing more in relation to FUOTA. 

I have also tested the FUOTA with a smaller update. In one case I had a update with 2kB and **the stack was able to reconstruct the packet, although 2 packets were lost**.

I have attached the log and the following screenshot.
![FUOTA_Test_08 11 2023_stack_event_no_more_multicast_xx](https://github.com/Lora-net/SWL2001/assets/127117112/20639183-6ec5-41c8-a786-a643b675f75a)

[FUOTA_Test_08.11.2023_stack_log_at_start.txt](https://github.com/Lora-net/SWL2001/files/13307878/FUOTA_Test_08.11.2023_stack_log_at_start.txt)

Generally the issue is that in most cases, at least one packet is missed at the beginning of the FUOTA. As soon as all fragments have been received (in my case: 783 fragments + 2 more fragments), the stack generates **no** FUOTA event (`SMTC_MODEM_EVENT_LORAWAN_FUOTA_DONE`). 

The next problem is that Stack does not reconstruct the update if at least a package got lost.

Could it be that the packets are lost at the beginning due to an error in the timing accuracy? Or is there perhaps a bug in the stack?

**Comment by lbm-team** [comment]
Hi @Ramin-Mardani,

A new version of LoRa Basics Modem has been released [v4.3.0](https://github.com/Lora-net/SWL2001/tree/v4.3.0)  
Could you try and check if it solves your issue?
