### ISSUE TITLE
The stack reports a warning in relation to FcntDwn while a FUOTA is running

### ISSUE THREAD

**Issue by Ramin-Mardani** [Lora-net/SWL2001#24]
I have the same configuration/setting like in issue https://github.com/Lora-net/SWL2001/issues/23

Sometimes the stack reports the following warning. This disappears after receiving a few more fragments.

![FUOTA_warning_FcntDwn](https://github.com/Lora-net/SWL2001/assets/127117112/d5e9964b-6ef1-4df5-8f88-ca4913f1f615)

**Comment by lbm-team** [comment]
Hi @Ramin-Mardani,

A new version of LoRa Basics Modem has been released [v4.3.0](https://github.com/Lora-net/SWL2001/tree/v4.3.0)
Could you try and check if it solves your issue?
