### ISSUE TITLE
EndDeviceConfReq does not correctly parse backoff field

### ISSUE THREAD

**Issue by adriansmares** [Lora-net/SWL2001#28]
When LBM is compiled with relay TX support, the parsers for the `EndDeviceConfReq` MAC command considers the backoff field to be 5 bits long:

https://github.com/Lora-net/SWL2001/blob/c4f386ac54b3e35f45b8ba7502207faa6f634921/smtc_modem_core/lr1mac/src/relay/relay_tx/relay_tx_mac_parser.c#L124

The backoff field has a range of 0 to 63 - is actually 6 bits long:

<img width="604" alt="image" src="https://github.com/Lora-net/SWL2001/assets/36161392/e6d82c25-182d-442e-9b92-f0f8e3962007">

**Comment by lbm-team** [comment]
Hello,

This issue was solved in the release v4.4.0-feature-relay.
