### ISSUE TITLE
NucleoL476 LR1121 Board Not Switching to Class B Despite Configuration

### ISSUE THREAD

**Issue by leofabri** [Lora-net/SWL2001#50]
I'm currently working on a project involving the NucleoL476 LR1121 board, aiming to operate it in Class B mode. I have verified that the beacon is successfully transmitted by the gateway, and I have configured my network server (TTN) to use Class B. However, despite these configurations, I'm unable to see the device switch to this mode.

## My Gateway (_global_conf.json_):
![image](https://github.com/Lora-net/SWL2001/assets/10175326/72264619-334f-46d1-9414-57fbd50d242f)

## TTN Configuration:
- ![image](https://github.com/Lora-net/SWL2001/assets/10175326/7dfb26bb-c537-4006-b834-3914d3e6b22f)
- ![image](https://github.com/Lora-net/SWL2001/assets/10175326/d9ceb31d-f465-4211-a015-935ca4b65579)

## Device Details:

- Board: NucleoL476 LR1121
- Firmware/Software Version: v4.3.0

## Reproduction Steps

- Verified beacon transmission from the gateway:
```
Mar 15 14:59:39 os lora_pkt_fwd[129114]: ### [JIT] ###
Mar 15 14:59:39 os lora_pkt_fwd[129114]: src/jitqueue.c:444:jit_print_queue(): INFO: [jit] queue contains 3 beacons:
Mar 15 14:59:39 os lora_pkt_fwd[129114]: src/jitqueue.c:448:jit_print_queue():  - node[0]: count_us=2765857177 - type=3
Mar 15 14:59:39 os lora_pkt_fwd[129114]: src/jitqueue.c:448:jit_print_queue():  - node[1]: count_us=2893857580 - type=3
Mar 15 14:59:39 os lora_pkt_fwd[129114]: src/jitqueue.c:448:jit_print_queue():  - node[2]: count_us=3021857597 - type=3
Mar 15 15:00:39 os lora_pkt_fwd[129114]: ### SX1302 Status ###
Mar 15 15:00:39 os lora_pkt_fwd[129114]: # BEACON queued: 24
Mar 15 15:00:39 os lora_pkt_fwd[129114]: # BEACON sent so far: 21
Mar 15 15:00:39 os lora_pkt_fwd[129114]: # BEACON rejected: 0
Mar 15 15:00:39 os lora_pkt_fwd[129114]: INFO: Beacon dequeued (count_us=2765857177)
Mar 15 15:00:39 os lora_pkt_fwd[129114]: INFO: Beacon queued (count_us=3149857230, freq_hz=869525000, size=17):
Mar 15 15:01:12 os lora_pkt_fwd[129114]: ### SX1302 Status ###
Mar 15 15:01:12 os lora_pkt_fwd[129114]: # BEACON queued: 25
Mar 15 15:01:12 os lora_pkt_fwd[129114]: # BEACON sent so far: 22
Mar 15 15:01:12 os lora_pkt_fwd[129114]: # BEACON rejected: 0
Mar 15 15:02:09 os lora_pkt_fwd[129114]: ### SX1302 Status ###
Mar 15 15:02:09 os lora_pkt_fwd[129114]: # BEACON queued: 25
Mar 15 15:02:09 os lora_pkt_fwd[129114]: # BEACON sent so far: 22
Mar 15 15:02:09 os lora_pkt_fwd[129114]: # BEACON rejected: 0
```

- Configured TTN for Class B operation as per screenshots.
- Compiled the project with the following command:
```
make -C lbm_examples full_lr1110 MODEM_APP=PERIODICAL_UPLINK LBM_CLASS_B=yes
```

## Expected Behavior

The device should switch to Class B mode, allowing for scheduled receive windows in addition to Class A's random receive windows.

## Actual Behavior

The device does not switch to Class B mode. No indication of Class B operation or scheduled receive windows observed.

## Request for Assistance

I am seeking guidance on how to properly configure my setup for Class B operation or if there are any known issues or additional steps required for the NucleoL476 LR1121 board to operate in Class B with TTN.

Thank you in advance for your support and assistance.

**Comment by lbm-team** [comment]
Hi leofabri,
in you application code have you set the class B with the API ?
```c
smtc_modem_return_code_t smtc_modem_set_class( uint8_t stack_id, smtc_modem_class_t lorawan_class )
```

Best Regards
