### ISSUE TITLE
Makefile ignores MCU_FLAGS

### ISSUE THREAD

**Issue by metamaterialsuit** [Lora-net/SWL2001#51]
The issue was first mentioned and fixed here: [Makefile Ignores MCU_FLAGS](https://github.com/Lora-net/SWL2001/issues/5#issue-1419373562
)
The issue has again resurfaced here [options.mk]( https://github.com/Lora-net/SWL2001/blob/5b1839eca726b3e18307facfbc29fed0e13b2c11/lbm_lib/makefiles/options.mk)

**Comment by lbm-team** [comment]
Hi Metamaterialsuit,
The flag will fixed in next release,
Thank you

Best
