### ISSUE TITLE
SX1276 How experimental?

### ISSUE THREAD

**Issue by JohnTordur** [Lora-net/SWL2001#58]
I'm looking to implement a simple Class A node, using SX1276 (RFM95) on a custom PCB. Why is it marked experimental, how useful is it in practice compared to another radio?

**Comment by gonzabrusco** [comment]
I was wondering the same. Why does this Semtech module have less support?

**Comment by Kyrunix** [comment]
Even if this question is older, take a look at this:
https://github.com/Lora-net/SWL2001/blob/master/lbm_lib/README.md#sx1272sx1276-experimental

it might be the answer

**Comment by opeyrard** [comment]
Thanks for your contribution Kyrunix.
Issue can be closed.
