### ISSUE TITLE
Modem charge mAh with different configuration

### ISSUE THREAD

**Issue by RobTWTG** [Lora-net/SWL2001#61]
I noticed that when ral_get_lora_rx_consumption_in_ua is called. rx_boosted is always set to false.

Our PCB uses the sx1261 powered with a 1.8V power supply, the implementation to track consumption only uses the table for a 3.3V power supply.

Will there be an implementation in the future to track the power using rx_boosted and 1.8V?

**Comment by opeyrard** [comment]
This limitation is confirmed and will be fixed in the next SWL2001 release.
