### ISSUE TITLE
aes_encrypt duplicate definition linking error + ideas for fix

### ISSUE THREAD

**Issue by cmorganBE** [Lora-net/SWL2001#68]
aes_encrypt() symbol is a common one, wolfssl and/or some other ssl modules appear to define the same symbol.

Would it be acceptable to rename the public functions in aes.h to add a 'lora_' prefix? like lora_aes_encrypt()?

If so I can open a PR with said change.

I'm guessing there *may* be ways to fix this with various build options but that seemed like a significant amount of additional effort, although fewer changes to the stack here.

Thoughts? We'd like to not carry any local changes around (and today we've renamed aes_encrypt() to lora_aes_encrypt() to resolve this issue).

**Comment by opeyrard** [comment]
Hi,
We will evaluate feasibility for the next release.
Many thanks,
