### ISSUE TITLE
Compilation flags include an ARM-specific flag

### ISSUE THREAD

**Issue by tcbennun** [Lora-net/SWL2001#7]
Howdy folks. We're starting our journey in porting this stack to the Espressif family of chips. So far, so good.

Minor thing: I've had to locally modify `common.mk` to remove an ARM-specific compile flag:

https://github.com/Lora-net/SWL2001/blob/8d052b21f39344a543c15e29d76dfab2cc9eb709/makefiles/common.mk#L181

To maximise compatibility I'd recommend not including this flag by default!

This modification aside, the stack builds fine under the Espressif compiler. Cheers.

-----

P.S. Quick question: is there any plan to use CMake in addition to / instead of make in the future?

**Comment by lbm-team** [comment]
Hi @tcbennun !  
This issue is now solved in the v3.3.0 release of the project.  
The specific MCU compile flag has been removed.
