### ISSUE TITLE
Possible bug in the GET_STATUS command

### ISSUE THREAD

**Issue by rdaubencd** [Lora-net/SWL2001#8]
There is a possible bug in the GET_STATUS command, implemented in smtc_modem_core\radio_drivers\sx126x_driver\src\sx126x.c:sx126x_get_status().  The command should send two bytes and include a NOP byte after the command byte.  The macro SX126X_SIZE_GET_STATUS should be changed to “2”.

**Comment by matthieuantoine** [comment]
Hi @rdaubencd,

According to the datasheet v2.1 (see below an extract), the implementation is correct.

![image](https://user-images.githubusercontent.com/44699865/223186420-90ad6bdb-1a10-4101-8cae-76728cfc7be8.png)

**Comment by rdaubencd** [comment]
The current value is 1:

https://github.com/Lora-net/SWL2001/blob/master/smtc_modem_core/radio_drivers/sx126x_driver/src/sx126x.c, line 183.

But as you point out from the data sheet, two bytes should be sent out: 0xC0, 0x00.

Therefore, the size used in line 814 is SX126X_SIZE_GET_STATUS, which should be 2.

What else am I missing?  Has this already been fixed in another branch?

**Comment by matthieuantoine** [comment]
The way `sx126x_hal_read` is used is the following:

- Send `command_length` bytes from `command` buffer
- Receive `data_length` bytes in `data` buffer

In `sx126x_get_status` implementation, `sx126x_hal_read` is called with the following values:

- `command_length` = 1
- `data_length` = 1

In the end, there are effectively **2 bytes** exchanged over SPI.

**Comment by rdaubencd** [comment]
I believe the command_length needs to be 2 to write out the opcode and NOP.  The data_length is 1 to read back the status byte. That's 3 bytes of data exchanged.  I had to make the change to get my test app to read the correct status. 

Compare this to the next function in the file sx126x_get_rx_buffer_status(), which correctly adds the NOP byte to the outgoing 2-byte buffer.

Anyway, thanks for your feedback.
