### ISSUE TITLE
2.4GHz is not working for LR1121 with STML476RG MCU

### ISSUE THREAD

**Issue by milkias99** [Lora-net/SWL2001#83]
I compiled the project with make lr1121 REGION=WW_2G4, but it still uses 915MHz instead of 2.4GHz. Could it be that the project doesn't include the necessary configuration for LR1121 to operate at 2.4GHz?

**Comment by lbm-team** [comment]
can you try adding these lines in the file [lbm_lib/makefiles/regions.mk](https://github.com/Lora-net/SWL2001/blob/master/lbm_lib/makefiles/regions.mk)

after the line 32:

ifeq ($(RADIO),lr1121)
REGION_WW_2G4 = yes
endif

thank you for your feedback
